FROM golang:1.17-bullseye AS golib
FROM ubuntu:20.04

# Install build-essential in case it is needed for node cuz its nOoOdDEe.
RUN apt-get update && apt-get upgrade -y && TZ="America/New_York" DEBIAN_FRONTEND="noninteractive" apt-get install -y software-properties-common tzdata python3-pip build-essential git ssh nano zsh curl && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache --upgrade pip setuptools wheel

# Install npm
RUN touch /root/.zshrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN bash -c "source /root/.nvm/nvm.sh && nvm install 16 && nvm use default 16"

# Install Go
COPY --from=golib /usr/local/go /usr/local/go
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
RUN go install github.com/githubnemo/CompileDaemon@v1.4.0
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
RUN go install github.com/swaggo/swag/cmd/swag@v1.7.6

# Specific Node side of stuff below
RUN bash -c "source /root/.nvm/nvm.sh && npm i -g pnpm"

# Dev specific tweaks and final commands
ENV EDITOR=nano
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN chsh -s /bin/zsh
VOLUME /src/
WORKDIR /src/
