FROM golang:1.17-alpine AS golib
FROM golangci/golangci-lint:v1.43.0 AS linter
FROM node:16-alpine

# Install python in case it is needed for node cuz its NODE.
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 make build-base && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools wheel

# Install Go
COPY --from=golib /usr/local/go /usr/local/go
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
RUN go install github.com/githubnemo/CompileDaemon@v1.4.0
# RUN CGO_ENABLED=0 go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
COPY --from=linter /usr/bin/golangci-lint /usr/bin/golangci-lint
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Specific Node side of stuff below
RUN npm i -g pnpm

# Dev specific tweaks and final commands
RUN apk add --no-cache git openssh alpine-sdk
VOLUME /src/
WORKDIR /src/
CMD ./run_dev.sh