FROM node:16-alpine
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 make build-base && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools wheel
RUN npm install -g npm
RUN npm config set python "$(which python3)"