name: docker-publish-bananas

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Post Job status on discord
        run: |
          curl --location --request POST ${{ secrets.DISCORD_WEBHOOK }} --header 'Content-Type: application/json' --data-raw '{"content": "Build #${{ github.run_number }}: Docker build execution started for bananas."}'
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-bananas-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bananas-buildx-
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push bananas
        run: |
          docker buildx build --pull --no-cache --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USER }}/bananas:$(date +"%Y%m%d") -t ${{ secrets.DOCKER_USER }}/bananas:latest --push -f ./bananas/Dockerfile.dev --cache-from type=local,src=/tmp/.buildx-cache/bananas --cache-to type=local,dest=/tmp/.buildx-cache-new/bananas ./bananas/
      -
        # Temp fix 
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - 
        name: Post Job status on discord
        if: always()
        run: |
          curl --location --request POST ${{ secrets.DISCORD_WEBHOOK }} --header 'Content-Type: application/json' --data-raw '{"content": "Build #${{ github.run_number }}: ${{ job.status }} for bananas"}'